#!/bin/sh
# install zsh
pacman -S zsh
# install oh-my-zsh (theme manager)
export ZSH=/opt/oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
ZSH_PATH=/opt/oh-my-zsh
# install autosuggestions plugin
git clone https://github.com/zsh-users/zsh-autosuggestions.git $ZSH_PATH/plugins/zsh-autosuggestions
echo $ZSH_PATH
# install syntax highlighting plugin
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH_PATH/plugins/zsh-syntax-highlighting
echo $ZSH_PATH
# copy theme
cp src/kawaii.zsh-theme $ZSH_PATH/themes/kawaii.zsh-theme
echo $ZSH_PATH
# change shell
# chsh -s $(which zsh)
# copy .zshrc
cp src/.zshrc /etc/skel/.zshrc
