#!/bin/sh
# install zsh
pacman -S zsh
# install oh-my-zsh (theme manager)
export ZSH=/opt/oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
echo "$ZSH"
# install autosuggestions plugin
git clone https://github.com/zsh-users/zsh-autosuggestions.git $ZSH/plugins/zsh-autosuggestions
echo "$ZSH"
# install syntax highlighting plugin
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH/plugins/zsh-syntax-highlighting
echo "$ZSH"
# copy theme
cp src/kawaii.zsh-theme $ZSH/themes/kawaii.zsh-theme
echo "$ZSH"
# change shell
# chsh -s $(which zsh)
# copy .zshrc
cp src/.zshrc /etc/skel/.zshrc
