#!/bin/sh
ZSH_PATH=/opt/oh-my-zsh
# install autosuggestions plugin
git clone https://github.com/zsh-users/zsh-autosuggestions.git $ZSH_PATH/plugins/zsh-autosuggestions
# install syntax highlighting plugin
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH_PATH/plugins/zsh-syntax-highlighting
# copy theme
cp src/kawaii.zsh-theme $ZSH_PATH/themes/kawaii.zsh-theme
# change shell
# chsh -s $(which zsh)
# copy .zshrc
cp src/.zshrc /etc/skel/.zshrc
