#!/bin/bash
#rm -rf /usr/share/color-themes
#rm -rf /usr/share/konsole
#rm -rf /usr/share/plasma/look-and-feel
#rm -rf /usr/share/sddm
#rm -rf /usr/share/wallpapers
cp -r src/* /
plasma-apply-lookandfeel Kawaii
plasma-apply-wallpaperimage /usr/share/wallpapers/Kawaii/contents/images/2560x1440.jpg
